### ISSUE TITLE
EventStore 20.6.0 - Connection lost to /127.0.0.1:1113: sink disconnected

### ISSUE THREAD

**Issue by MichaelMedvedskiy** [EventStore/EventStore.JVM#155]
Hey. I'm running a docker-compose installation of EventStore, version 20.6.0, for development purposes:
```
version: '3.4'

services:
  db:
    image: eventstore/eventstore:20.6.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_DEV=true
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"

```

Since this is the 20.6.0 version, the only way I can get access to the EventStore on a request-response basis is HTTPS (correct me if I'm wrong). I've managed to get access to the Web-UI (2113 port, required adding "EVENTSTORE_DEV=true"), I've managed to even make the REST API work via Postman.
I dev in Java, and I tried to run the "Write event example" from the EventStore.JVM README.

Having _"com.geteventstore:eventstore-client_2.13:7.1.0"_ as a dependency, I run the example, it repetitively prints the following 2 messages repetitively:
```
[INFO] [06/18/2020 03:19:51.795] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] Connected to /127.0.0.1:1113 [WARN] [06/18/2020 03:19:51.809] [default-akka.actor.default-dispatcher-9] [akka://default/user/$a] Connection lost to /127.0.0.1:1113: sink disconnected [INFO] [06/18/2020 03:19:52.090] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] Connected to /127.0.0.1:1113 [WARN] [06/18/2020 03:19:52.094] [default-akka.actor.default-dispatcher-9] [akka://default/user/$a] Connection lost to /127.0.0.1:1113: sink disconnected [INFO] [06/18/2020 03:19:52.371] [default-akka.actor.default-dispatcher-9] [akka://default/user/$a] Connected to /127.0.0.1:1113 [WARN] [06/18/2020 03:19:52.374] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] Connection lost to /127.0.0.1:1113: sink disconnected [INFO] [06/18/2020 03:19:52.648] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] Connected to /127.0.0.1:1113 [WARN] [06/18/2020 03:19:52.651] [default-akka.actor.default-dispatcher-8] [akka://default/user/$a] Connection lost to /127.0.0.1:1113: sink disconnected [INFO] [06/18/2020 03:19:52.919] [default-akka.actor.default-dispatcher-6] [akka://default/user/$a] Connected to /127.0.0.1:1113
```

and approximately after 8 min of these messages being printed, the third one comes into the mix, and now there are 3 of those being repetitively printed:
```
[WARN] [06/18/2020 03:30:50.428] [default-akka.actor.default-dispatcher-5] [akka://default/user/$a] Connection lost to /127.0.0.1:1113: akka.stream.StreamTcpException: The connection closed with error: Connection reset
```

My guess is the JVM client trying to use HTTP, fails, retries. Correct me if my guess is wrong. And is there a way to make the JVM client properly communicate with the EventStore?
